// src/components/cards/album-search.tsx
export default function AlbumSearchCard({ album }: { album: any }) {
    const backendUrl = process.env.NEXT_PUBLIC_BACKEND_URL;

    return (
        <div className="flex flex-row gap-2 overflow-hidden py-2 w-full">
            <a
                href={`/albums/${album.id}/${album.slug}`}
                className="group flex w-full overflow-hidden cursor-pointer relative items-start">

                {/* Cover Image */}
                <img
                    src={album.image ? `${backendUrl}${album.image}` : 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg'}
                    alt={album.title}
                    className="w-12 h-12 lg:w-16 lg:h-16 rounded-sm object-cover"
                />

                {/* Album Detail */}
                <div className="flex flex-col px-2">
                    <h3 className="text-base md:text-lg font-medium text-dark line-clamp-1 group-hover:text-blue-500">
                        {album.title }
                    </h3>
                    <h2 className="text-sm md:text-base font-normal text-gray-500 line-clamp-1">
                        {album.artist.name}
                    </h2>
                </div>
            </a>
        </div>
    );
};

// components/cards/AlbumSearch.vue
<script setup>
const config = useRuntimeConfig();
const backendUrl = config.public.backendUrl;

defineProps({
    album: {
        type: Object,
        required: true,
        validator(album) {
            return album &&
                typeof album.title === 'string' &&
                typeof album.id !== 'undefined' &&
                typeof album.slug !== 'undefined';
        }
    },
});
</script>

<template>
    <NuxtLink :to="`/albums/${album.id}/${album.slug}`"
        class="group flex w-full overflow-hidden cursor-pointer relative items-center">
        <!-- Cover Image -->
        <img :src="`${backendUrl}${album.image}` || 'https://img.freepik.com/premium-vector/default-image-icon-vector-missing-picture-page-website-design-mobile-app-no-photo-available_87543-11093.jpg'"
            :alt="album.title" class="w-10 h-10 lg:w-12 lg:h-12 rounded-sm object-cover" />

        <!-- Album Title + Artist Name -->
        <div class="flex flex-col px-2">
            <h3 class="text-base md:text-lg font-medium text-dark line-clamp-1 group-hover:underline">
                {{ album.title }}
            </h3>
            <h2 class="text-sm md:text-base font-normal text-gray-500 line-clamp-1">
                {{ album.artist.name }}
            </h2>
        </div>
    </NuxtLink>
</template>
