// src/app/search/page.tsx
import AlbumSearchCard from "@/components/cards/album-search";
import ArtistSearchCard from "@/components/cards/artist-search";
import SongSearchCard from "@/components/cards/song-search";
import { Suspense } from "react";

const backendApiUrl = process.env.NEXT_PUBLIC_BACKEND_API_URL;

async function getSearchResults(q?: string) {
    if (!q) return { artists: [], albums: [], songs: [] };

    try {
        // Simulasi Shimmer delay
        // await new Promise(resolve => setTimeout(resolve, 2000));

        const res = await fetch(`${backendApiUrl}/search?query=${q.toLowerCase()}`, {
            cache: "no-store",
        });

        if (!res.ok) {
            throw new Error(`Failed to fetch search: ${res.status} ${res.statusText}`);
        }

        const jsonResponse = await res.json();

        return {
            artists: jsonResponse.data.artists || [],
            albums: jsonResponse.data.albums || [],
            songs: jsonResponse.data.songs || [],
        };
    } catch {
        throw new Error("An unexpected error occurred.");
    }
}

async function SearchResult({ q }: { q?: string }) {
    const { artists, albums, songs } = await getSearchResults(q);

    return q ? (
        <div className="container py-4 px-4 md:px-6 lg:px-8 xl:px-10 w-full min-h-[50vh]">
            <h1 className="text-xl lg:text-2xl font-bold text-dark truncate mb-2">
                Search result for: {q}
            </h1>

            {artists.length > 0 && (
                <div>
                    <h2 className="text-xl md:text-2xl text-dark font-bold mb-1">Artists</h2>
                    <div className="space-y-2">
                        {artists.map((artist: any) => (
                            <ArtistSearchCard key={artist.id} artist={artist} />
                        ))}
                    </div>
                </div>
            )}

            {albums.length > 0 && (
                <div>
                    <h2 className="text-xl md:text-2xl text-dark font-bold mb-1">Albums</h2>
                    <div className="space-y-2">
                        {albums.map((album: any) => (
                            <AlbumSearchCard key={album.id} album={album} />
                        ))}
                    </div>
                </div>
            )}

            {songs.length > 0 && (
                <div>
                    <h2 className="text-xl md:text-2xl text-dark font-bold mb-1">Songs</h2>
                    <div className="space-y-2">
                        {songs.map((song: any) => (
                            <SongSearchCard key={song.id} song={song} />
                        ))}
                    </div>
                </div>
            )}

            {artists.length === 0 && albums.length === 0 && songs.length === 0 && (
                <div className="flex justify-center items-center gap-2 h-[30svh]">
                    <div className="bg-red-200 w-fit p-2 rounded-full">
                        <svg className="h-4 w-4 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                        </svg>
                    </div>
                    <p className="text-base lg:text-lg font-normal text-dark truncate">
                        Sorry, we couldn't find what you were looking for
                    </p>
                </div>
            )}
        </div>
    ) : (
        <div className="flex justify-center items-center gap-2 h-[50svh]">
            <div className="bg-blue-100 w-fit p-2 rounded-full">
                <svg className="h-4 w-4 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
            </div>
            <p className="text-base lg:text-lg font-normal text-dark truncate">
                Search songs, albums, or artists
            </p>
        </div>
    );
}

export default async function SearchPage({
    searchParams
}: {
    searchParams: Promise<{ q?: string }>;
}) {
    const { q } = await searchParams;
    return (
        <Suspense fallback={
            <div className="w-full min-h-[60vh] flex items-center justify-center text-blue-500 text-4xl">
                <svg aria-hidden="true" className="inline w-8 h-8 text-gray-400 animate-spin fill-blue-500" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor" />
                    <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill" />
                </svg>
            </div>
        }>
            <SearchResult q={q} />
        </Suspense>
    )
}

// pages/search/index.vue
<script setup>
import { ref, watch } from 'vue';
import { useRoute } from 'vue-router';

// Reactive state variables
const query = ref('');
const artists = ref([]);
const albums = ref([]);
const songs = ref([]);
const fetchStatus = ref('');

// Use the route to access query parameters
const route = useRoute();

// Fetch initial data using useAPI
const { status, data: results } = await useAPI('/search', {
    query: {
        query: query.value,
    },
});

fetchStatus.value = status.value;

artists.value = results?.value?.data?.artists;
albums.value = results?.value?.data?.albums;
songs.value = results?.value?.data?.songs;

// Watch for query changes in the route
watch(
    () => route.query.q,
    async (newQuery) => {
        query.value = newQuery || ''; // Handle null/undefined case
        if (query.value) {
            fetchStatus.value = 'pending';
            try {
                const results = await $fetch('/search', {
                    baseURL: useRuntimeConfig().public.backendApiUrl,
                    params: {
                        query: query.value,
                    },
                });
                artists.value = results?.data?.artists || [];
                albums.value = results?.data?.albums || [];
                songs.value = results?.data?.songs || [];
                fetchStatus.value = 'success';
            } catch (error) {
                console.error(error);
                fetchStatus.value = 'error';
            }
        } else {
            // Reset state when no query
            artists.value = [];
            albums.value = [];
            songs.value = [];
            fetchStatus.value = '';
        }
    },
    { immediate: true } // Trigger immediately on component initialization
);
</script>


<template>
    <div class="container py-4 px-4 md:px-6 lg:px-8 xl:px-10 w-full min-h-[50vh]">

        <h1 v-if="query" class="text-xl lg:text-2xl font-bold text-dark truncate mb-2">
            Search result for: {{ query }}
        </h1>

        <div v-if="!query"
            class="flex justify-center items-center gap-2 h-[30svh]">
            <div class="bg-blue-200 w-fit p-2 rounded-full">
                <svg class="h-4 w-4 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
            </div>
            <p class="text-base lg:text-lg font-normal text-dark truncate">
                Search songs, albums, or artists
            </p>
        </div>

        <!-- Search Result -->
        <div v-if="fetchStatus === 'pending'">
            <div class="animate-spin rounded-full h-8 w-4 md:h-8 md:w-8 lg:h-12 lg:w-12 border-b-2 border-gray-500">
            </div>
        </div>

        <div v-else class="space-y-8">

            <!-- Nothing Found -->
            <div v-if="query && !artists.length && !albums.length && !songs.length"
                class="flex justify-center items-center gap-2 h-[30svh]">
                <div class="bg-red-200 w-fit p-2 rounded-full">
                    <svg class="h-4 w-4 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                    </svg>
                </div>
                <p class="text-base lg:text-lg font-normal text-dark truncate">
                    Sorry, we couldn't find what you were looking for
                </p>
            </div>

            <!-- Artist Section -->
            <div v-if="artists.length" class="mb-6">
                <h2 class="text-xl md:text-2xl text-dark font-bold mb-1">Artists</h2>
                <div class="space-y-2">
                    <CardsArtistSearch v-for="artist in artists" :key="artist.id" :artist="artist" />
                </div>
            </div>

            <!-- Albums Section -->
            <div v-if="albums.length" class="mb-6">
                <h2 class="text-xl md:text-2xl  text-dark font-bold mb-1">Albums</h2>
                <div class="space-y-2">
                    <CardsAlbumSearch v-for="album in albums" :key="album.id" :album="album" />
                </div>
            </div>

            <!-- Songs Section -->
            <div v-if="songs.length" class="mb-6">
                <h2 class="text-xl md:text-2xl  text-dark font-bold mb-1">Songs</h2>
                <div class="space-y-2">
                    <CardsSongSearch v-for="song in songs" :key="song.id" :song="song" />
                </div>
            </div>
        </div>
    </div>
</template>
