// pages/songs/[id]/[slug].vue
<script setup>
const route = useRoute();
const id = route.params.id;
const slug = route.params.slug;
const config = useRuntimeConfig();
const baseUrl = config.public.baseUrl;
const backendUrl = config.public.backendUrl;

const { statusSong, data: song } = await useAPI('/songs', {
    query: {
        id: id,
    },

});

if (!song.value?.data) {
    throw createError({
        statusCode: 404,
        message: "Song Not Found",
    })
}

if (song.value.data.slug !== slug) {
    // Perbarui URL tanpa reload halaman
    navigateTo({
        path: `/songs/${id}/${song.value.data.slug}`,
    });
}

// SEO Meta
useSeoMeta({
    title: () =>
        `${song.value.data.title} by ${song.value.data.artist.name} - Lyrics & Translations | TransLyrics`,
    keywords: () =>
        `${song.value.data.title}, ${song.value.data.original_title}, ${song.value.data.artist.name}, Japanese songs, song translations, song lyrics, lyrics translations, English translations, Romaji translations, Indonesian translations, TransLyrics`,
    description: () =>
        `Explore the song "${song.value.data.title}" by ${song.value.data.artist.name}${song.value.data.album?.title ? ` from the album "${song.value.data.album.title}"` : ''
        }. Find lyrics with translations to English, Romaji, and Indonesian. Discover the beauty of Japanese music with accurate translations.`,
    ogTitle: () =>
        `${song.value.data.title} by ${song.value.data.artist.name} - Lyrics & Translations | TransLyrics`,
    ogDescription: () =>
        `Find information about the song "${song.value.data.title}" by ${song.value.data.artist.name}${song.value.data.album?.title ? ` from the album "${song.value.data.album.title}"` : ''
        }, including lyrics and translations into English, Romaji, and Indonesian.`,
    ogImage: () =>
        `${backendUrl}${song.value.data.image}` || 'https://img.freepik.com/premium-vector/default-image-icon-vector-missing-picture-page-website-design-mobile-app-no-photo-available_87543-11093.jpg',
    ogUrl: () =>
        `${baseUrl}/songs/${song.value.data.id}/${song.value.data.slug}`,
    twitterCard:
        'summary_large_image',
    twitterTitle: () =>
        `${song.value.data.title} by ${song.value.data.artist.name} - Lyrics & Translations | TransLyrics`,
    twitterDescription: () =>
        `Discover the song "${song.value.data.title}" by ${song.value.data.artist.name}${song.value.data.album?.title ? ` from the album "${song.value.data.album.title}"` : ''
        }, featuring lyrics and translations in multiple languages. Explore now!`,
    twitterImage: () =>
        `${backendUrl}${song.value.data.image}` || 'https://img.freepik.com/premium-vector/default-image-icon-vector-missing-picture-page-website-design-mobile-app-no-photo-available_87543-11093.jpg',
    canonical: () =>
        `${baseUrl}/songs/${song.value.data.id}/${song.value.data.slug}`,
});

</script>

<template>
    <div class="container min-h-[50vh]">

        <p>{{ statusSong }}</p>
        <!-- Song Information -->
        <div>
            <SongDetailSectionInformationShimmer v-if="statusSong === 'pending'" />
            <SongDetailSectionInformation v-if="song?.data" :key="song.data.id" :song="song.data" />
        </div>

        <!-- Lyrics and Listen Platform -->
        <div class="flex flex-col lg:flex-row">
            <SongDetailSectionLyrics v-if="song?.data" :key="song.data.id" :song="song.data" />
            <SongDetailSectionListenPlatform v-if="song?.data" :key="song.data.id" :song="song.data" />
        </div>

    </div>
</template>

// src/app/songs/[id]/[slug]/page.tsx
export const dynamic = "force-dynamic";

import SongInfo from "@/components/song/song-info";
import SongInfoShimmer from "@/components/song/song-info-shimmer";
import SongLyrics from "@/components/song/song-lyrics";
import SongPlatform from "@/components/song/song-platform";
import { Suspense } from "react";
import { redirect } from "next/navigation";

import { Metadata } from "next";

const siteUrl = process.env.NEXT_SITE_URL;
const siteName = process.env.NEXT_SITE_NAME
const backendUrl = process.env.NEXT_PUBLIC_BACKEND_URL;

export async function generateMetadata({
    params,
}: {
    params: Promise<{ id: string }>;
}): Promise<Metadata> {
    const { id } = await params;

    const song = await fetchSong(id);

    return {
        title: `${song.title} by ${song.artist.name} - Lyrics & Translations | TransLyrics`,
        description: `Explore the song "${song.title}" by ${song.artist.name}${song.album?.title ? ` from the album "${song.album.title}"` : ''}. Find lyrics with translations to English, Romaji, and Indonesian.`,
        openGraph: {
            title: `${song.title} by ${song.artist.name} - Lyrics & Translations | TransLyrics`,
            description: `Find information about the song "${song.title}" by ${song.artist.name}${song.album?.title ? ` from the album "${song.album.title}"` : ''}, including lyrics and translations into English, Romaji, and Indonesian.`,
            url: `${siteUrl}/songs/${song.id}/${song.slug}`,
            images: song.image ? `${backendUrl}${song.image}` : 'https://img.freepik.com/premium-vector/default-image-icon-vector-missing-picture-page-website-design-mobile-app-no-photo-available_87543-11093.jpg',
            siteName: `${siteName}`
        },
        twitter: {
            card: 'summary_large_image',
            title: `${song.title} by ${song.artist.name} - Lyrics & Translations | TransLyrics`,
            description: `Discover the song "${song.title}" by ${song.artist.name}${song.album?.title ? ` from the album "${song.album.title}"` : ''}, featuring lyrics and translations in multiple languages. Explore now!`,
            images: song.image ? `${backendUrl}${song.image}` : 'https://img.freepik.com/premium-vector/default-image-icon-vector-missing-picture-page-website-design-mobile-app-no-photo-available_87543-11093.jpg',
        },
        metadataBase: new URL(`${siteUrl}/songs/${song.id}/${song.slug}`)
    }
}

const backendApiUrl = process.env.NEXT_PUBLIC_BACKEND_API_URL;

async function fetchSong(id: string) {

    try {
        // Delay fetch simulation
        // await new Promise(resolve => setTimeout(resolve, 3000));

        const res = await fetch(`${backendApiUrl}/songs?id=${id}`, {
            cache: "no-store",
        });

        if (!res.ok) {
            throw new Error(`Failed to fetch song: ${res.status} ${res.statusText}`);
        }

        const jsonResponse = await res.json();
        const song = jsonResponse.data;

        if (!song) {
            throw new Error("Can't find the song you are looking for");
        }

        return song;
    } catch {
        throw new Error("An unexpected error occurred.");
    }

}

async function SongPageComponent({
    id,
    slug
}: {
    id: string;
    slug: string;
}) {
    const song = await fetchSong(id);

    // Redirect if slug not match
    if (slug !== song.slug) {
        redirect(`/songs/${id}/${song.slug}`);
    }

    return (
        <div className="container min-h-[50vh]">
            {/* Song Information */}
            <SongInfo song={song} />

            {/* Song Lyrics & Platform */}
            <div className="flex flex-col lg:flex-row">
                <SongLyrics lyrics={song.lyrics} />
                <SongPlatform song={song} />
            </div>
        </div>
    );
}

export default async function SongPage({
    params,
}: {
    params: Promise<{ id: string; slug: string }>;
}) {
    const { id, slug } = await params;

    return (
        <Suspense fallback={<SongInfoShimmer />}>
            <SongPageComponent id={id} slug={slug} />
        </Suspense>
    );
}
