// pages/albums/index.vue
<script setup>
const config = useRuntimeConfig();
const baseUrl = config.public.baseUrl;

const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

const { status, data: albums } = await useAPI('/albums', {
    query: {
        sort_by: 'title',
        direction: "asc"
    },
});

const scrollToSection = (letter) => {
    const element = document.getElementById(`section-${letter}`);
    if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
    }
};

const getAlbumsBySection = (letter) => {
    if (letter === '#') {
        return albums.value.data.filter(album => {
            const firstChar = album.title.charAt(0).toUpperCase();
            return !alphabet.includes(firstChar);
        });
    }

    return albums.value.data.filter(album => album.title.charAt(0).toUpperCase() === letter)
        .sort((a, b) => a.title.localeCompare(b.title));
};

useSeoMeta({
    title: () => `Albums - TransLyrics`,
    keywords: () =>
        `all albums, Japanese albums, album translations, song lyrics, lyrics translations, English translations, Romaji translations, Indonesian translations, TransLyrics`,
    description: () =>
        `Browse all the albums featured on TransLyrics, with lyrics translations in English, Romaji, and Indonesian.`,
    ogTitle: () => `Albums - TransLyrics`,
    ogDescription: () =>
        `Explore all the albums from various artists on TransLyrics, featuring songs with translations to English, Romaji, and Indonesian.`,
    ogUrl: () => `${baseUrl}/albums`,
    twitterCard: 'summary_large_image',
    twitterTitle: () => `Albums - TransLyrics`,
    twitterDescription: () =>
        `Discover all the albums on TransLyrics, with lyrics and translations in multiple languages.`,
    canonical: () => `${baseUrl}/albums`,
});

</script>


<template>
    <div class="container py-4 px-4 md:px-6 lg:px-8 xl:px-10">

        <h1 class="text-xl lg:text-2xl font-bold text-dark truncate mb-2">Album List</h1>

        <!-- Alphabet Navigation -->
        <div class="flex flex-wrap gap-2 py-4 mb-4">
            <button v-for="letter in ['#', ...alphabet]" :key="letter" @click="scrollToSection(letter)"
                class="w-6 h-6 md:w-8 md:h-8 flex items-center justify-center text-sm md:text-base bg-dark hover:bg-gray-900 text-light rounded ">
                {{ letter }}
            </button>
        </div>

        <!-- Album List Sections -->
        <div class="space-y-8">
            <!-- Special characters section -->
            <div :id="'section-#'" class="scroll-mt-24">
                <h2 class="text-xl text-dark font-bold mb-1">##</h2>
                <div v-if="getAlbumsBySection('#').length" class="space-y-2">
                    <CardsAlbumSearch v-for="album in getAlbumsBySection('#')" :key="album.id" :album="album" />
                </div>
                <p v-else class="text-gray-500">No album available at this time</p>
            </div>

            <!-- Alphabet sections -->
            <div v-for="letter in alphabet" :key="letter" :id="'section-' + letter" class="scroll-mt-24">
                <h2 class="text-xl text-dark font-bold mb-1">#{{ letter }}</h2>
                <div v-if="getAlbumsBySection(letter).length" class="space-y-2">
                    <CardsAlbumSearch v-for="album in getAlbumsBySection(letter)" :key="album.id" :album="album" />
                </div>
                <p v-else class="text-gray-500">No album available at this time</p>
            </div>
        </div>
    </div>
</template>

// src/app/albums/page.tsx
export const dynamic = "force-dynamic";

import AlbumSearchCard from "@/components/cards/album-search";
import AlphabetNavigation from "@/components/search/alphabet-navigation";
import { Suspense } from "react";

import { Metadata } from "next";

const siteUrl = process.env.NEXT_SITE_URL;
const siteName = process.env.NEXT_SITE_NAME

export const metadata: Metadata = {
    title: 'Albums - TransLyrics',
    description: 'Browse all the albums featured on TransLyrics, with lyrics translations in English, Romaji, and Indonesian.',
    openGraph: {
        title: 'Albums - TransLyrics',
        description: 'Explore all the albums from various artists on TransLyrics, featuring songs with translations to English, Romaji, and Indonesian.',
        url: `${siteUrl}/albums`,
        siteName: `${siteName}`
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Albums - TransLyrics',
        description: 'Discover all the albums on TransLyrics, with lyrics and translations in multiple languages.',
    },
    metadataBase: new URL(`${siteUrl}/albums`)
};

async function AlbumList() {
    const backendApiUrl = process.env.NEXT_PUBLIC_BACKEND_API_URL;
    const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

    try {
        // Delay fetch simulation
        // await new Promise(resolve => setTimeout(resolve, 3000));

        const res = await fetch(`${backendApiUrl}/albums?sort_by=title&direction=asc`,
            { cache: 'no-store' }
        );

        if (!res.ok) {
            throw new Error(`Failed to fetch albums: ${res.status} ${res.statusText}`);
        }

        const jsonResponse = await res.json();
        const albums = jsonResponse.data || [];

        const getAlbumsBySection = (letter: string) => {
            if (!albums) return [];
            if (letter === "#") {
                return albums.filter((album: any) => {
                    const firstChar = album.title.charAt(0).toUpperCase();
                    return !alphabet.includes(firstChar);
                });
            }
            return albums
                .filter((album: any) => album.title.charAt(0).toUpperCase() === letter)
                .sort((a: any, b: any) => a.title.localeCompare(b.title));
        };

        return (
            <div className="container py-4 px-4 md:px-6 lg:px-8 xl:px-10">
                <h1 className="text-xl lg:text-2xl font-bold text-dark truncate mb-2">Album List</h1>

                {/* Client Component untuk navigasi */}
                <AlphabetNavigation alphabet={alphabet} />

                {/* Album List Sections */}
                <div className="space-y-8">
                    {/* Special characters section */}
                    <div id="section-#" className="scroll-mt-24">
                        <h2 className="text-xl text-dark font-bold mb-1">##</h2>
                        {getAlbumsBySection("#").length > 0 ? (
                            <div className="space-y-2">
                                {getAlbumsBySection("#").map((album: any) => (
                                    <AlbumSearchCard key={album.id} album={album} />
                                ))}
                            </div>
                        ) : (
                            <p className="text-gray-500">No album available at this time</p>
                        )}
                    </div>

                    {/* Alphabet sections */}
                    {alphabet.map((letter) => (
                        <div key={letter} id={`section-${letter}`} className="scroll-mt-24">
                            <h2 className="text-xl text-dark font-bold mb-1">#{letter}</h2>
                            {getAlbumsBySection(letter).length > 0 ? (
                                <div className="space-y-2">
                                    {getAlbumsBySection(letter).map((album: any) => (
                                        <AlbumSearchCard key={album.id} album={album} />
                                    ))}
                                </div>
                            ) : (
                                <p className="text-gray-500">No album available at this time</p>
                            )}
                        </div>
                    ))}
                </div>
            </div>
        );
    } catch {
        throw new Error("An unexpected error occurred.");
    }

}

export default function AlbumsPage() {
    return (
        <Suspense fallback={
            <div className="w-full min-h-[60vh] flex items-center justify-center text-blue-500 text-4xl">
                <svg aria-hidden="true" className="inline w-8 h-8 text-gray-400 animate-spin fill-blue-500" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor" />
                    <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill" />
                </svg>
            </div>
        }>
            <AlbumList />
        </Suspense>
    );
}
